[workspace]
resolver = "3"
members = ["app", "backend", "shared-core", "rust-matc"]

default-members = ["app"]

[workspace.dependencies]
app.path = "app"
backend.path = "backend"
shared-core.path = "shared-core"
matc = { path = "rust-matc", features = ["ble"] }

matter-controller = { version = "0.7.1", features = ["ble"]}
matter-clusters = "0.4.1"
matter-interaction = "0.4.1"
matter-codec = "0.3.1"

dioxus = { version = "0.7.9", features = ["router", "fullstack"] }
dioxus-html = { version = "0.7.9", features = ["serialize"]}
dioxus-stores = { version = "0.7.9" }
dioxus-free-icons = { version = "0.10", features = [ "font-awesome-solid" ]}
web-sys = { version = "0.3.103", features = ["ToggleEvent"]}

serde = "1.0"
anyhow = "1.0"
futures = "0.3"
derive_more = "2.1"

notify = "8.2.0"
tokio = "1.53"
tokio-util = "0.7.19"
tokio-stream = "0.1.19"
hex = "0.4.3"

toml = "1.1.3+spec-1.1.0"
chrono = "0.4"
rand = "0.10.2"
either_of = "0.1.9"
itertools = "0.15"

getrandom_0_2_17 = { package = "getrandom", version = "0.2.17" }
getrandom_0_3_4 = { package = "getrandom", version = "0.3.4" }
getrandom_0_4_3 = { package = "getrandom", version = "0.4.3" }
