[package]
name = "shared-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus.workspace = true
dioxus-html.workspace = true
dioxus-stores.workspace = true
serde = { workspace = true, features = ["rc"]}
anyhow.workspace = true
futures.workspace = true
either_of.workspace = true
jiff.workspace = true

derive_more = { workspace = true, features = ["as_ref"] }
toml.workspace = true

matter-controller = { workspace = true, optional = true }
matter-clusters.workspace = true
matter-codec = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[features]
backend = [ "dep:matter-controller", "dep:matter-codec", "dep:tokio" ]
